"""
A coloured triangle is created from a row of colours, each of which is red, green or blue. 
Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. 
If these colours are identical, the same colour is used in the new row. 
If they are different, the missing colour is used in the new row. 
This is continued until the final row, with only a single colour, is generated.

The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
"""


def triangle(row):
    result = row
    while len(result) > 1:
        result = calculate_triangle(result)
    return result


def calculate_triangle(row):
    result_list = ""
    for i in range(len(row) - 1):
        result_list += next_color(row[i], row[i + 1])
    return result_list


def next_color(i, j):
    colors = ["R", "G", "B"]
    if i == j:
        return i
    else:
        colors.remove(i)
        colors.remove(j)
        return colors[0]
